import {generatePlan} from './generator.js';
const form=document.querySelector('#plan-form'),result=document.querySelector('#result'),status=document.querySelector('#status'),copy=document.querySelector('#copy');
const purposeSelect=form.elements.purpose,otherPurpose=form.elements.purposeOther;
function updatePurpose(){const isOther=purposeSelect.value==='other';document.querySelector('#other-purpose-field').hidden=!isOther;otherPurpose.disabled=!isOther;otherPurpose.required=isOther;}
purposeSelect.addEventListener('change',()=>{updatePurpose();if(purposeSelect.value==='other')otherPurpose.focus();});
updatePurpose();
let output='';
function block(title,body){const section=document.createElement('section');section.className='output-block';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=body;section.append(h,p);result.append(section);output+=`${title}\n${body}\n\n`;}
document.querySelector('#example').addEventListener('click',()=>{form.elements.theme.value='忙しい朝の簡単スキンケア\n洗顔では肌を強くこすらない\n保湿は肌の状態に合わせる\n日焼け止めを忘れずに使う';form.elements.target.value='美容初心者の20代女性';form.elements.purpose.value='保存してもらいたい';updatePurpose();form.elements.theme.focus();});
form.addEventListener('submit',event=>{event.preventDefault();try{const plan=generatePlan(Object.fromEntries(new FormData(form)));result.replaceChildren();output='';block(plan.format==='feed'?'表紙タイトル':'リールのタイトル',plan.title);if(plan.format==='feed'){plan.pages.forEach((page,i)=>block(`${i+1}ページ目｜${page.heading}`,page.body+'\n\n画像の提案：'+page.image+(page.cta?`\nCTA：${page.cta}`:'')));}else{block('冒頭3秒のフック',plan.hook);plan.scenes.forEach((scene,i)=>block(`シーン${i+1}｜${scene.time}`,`テロップ：${scene.text}\nおすすめの素材・映像：${scene.visual}\n静止画・デザインの提案：${scene.image}`));block('最後のCTA',plan.cta);}block('キャプション案',plan.caption);block('画像づくりの共通ガイド',plan.designGuide+'\nフィードは縦長の4:5、リールは9:16が目安です。リールの文字は上下の端を避けて配置しましょう。\n※ここで表示するのは画像のアイデアです。画像ファイルの生成は行いません。');document.querySelector('#empty').hidden=true;result.hidden=false;copy.hidden=false;status.textContent='構成案ができました。具体例を加えて仕上げましょう。';if(window.matchMedia('(max-width: 720px)').matches)document.querySelector('.result-card').scrollIntoView({behavior:'smooth',block:'start'});}catch(error){status.textContent=error.message;}});
copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(output);status.textContent='構成案をコピーしました。';}catch{status.textContent='自動コピーが利用できません。下の文章を選択してコピーしてください。';const area=document.createElement('textarea');area.value=output;area.setAttribute('aria-label','コピー用の構成案');result.replaceChildren(area);area.focus();area.select();}});
